### ISSUE TITLE
[FEATURE] Alternative Scoring and Threshold Adjustment for sklego.meta.ZeroInflatedRegressor

### ISSUE THREAD

**Issue by john-hawkins** [koaning/scikit-lego#479] opened 2021-08-27 10:20 UTC
I have been doing some experimentation with the Meta Model sklego.meta.ZeroInflatedRegressor

One of the key things I need to do is adjust the probability threshold at which a prediction is considered to be Zero or Non-Zero. This is critical because it allows me to calibrate the number of zeros output.

In addition, I am looking at alternative scoring methods. For example, that the output of the classifier model is used to modulate the output of the regression. So rather than final scoring being a Boolean choice between zero or regression model output, the output becomes prob_non_zero * Regression_output. This approach looks promising as a way to recalibrate a regression model that is slightly biased toward predictions on the high side.

I have an initial implementation of this, and I have set it up such that the default parameters will maintain current behaviour.

Cheers
John

**Comment by john-hawkins** [comment] 2021-08-28 03:18
Thanks @koaning 

Your summary is perfect.

The second idea is to mitigate the fact that the output of the classifier is not perfect. 
The classifier provides an estimate of the probability that true value is zero (or non-zero). 
In prediction mode the regression model is not outputting a direct estimate of the value, rather it is an estimate of the value conditional on it being non-zero.

So the key idea is to produce an output that is an expectation of the true value based on the probability that it is non-zero.
This would be:   
```P(Zero) * 0  + P(Non-Zero) * Y_hat```
Where Y_hat is the output of the regression model. 
The first term is not needed, I have just put it here to make it clear that what we are calculating is the expected value by using the probabilities of the first model.

I have found that this approach can provide a better model in situations where the classifier struggles to provide a clean separation between zero and non-zero, and the data is highly skewed.

**Comment by koaning** [comment] 2021-08-28 09:06
I see the point, but this turns the prediction into 'p(not zero) x y_hat',  correct?

Could you give a real life scenario where this'd be useful? In my mind, if uncertaity plays such a large role, wouldn't it be better to model in PyMC3?

**Comment by john-hawkins** [comment] 2021-08-28 23:47
Thanks @koaning 

Yes, that is correct. I only included the first term to make clear that what is being calculated is an expectation.

The use cases for this are the same as any use of the current zero inflated regression model: _zero inflated data sets where you want a point estimate_. This approach simply gives the user another hyper-parameter to test for whatever performance metric the user is tuning. I have personally found that it works well on  noisy, right skewed, zero inflated data.

I agree, that if what the user is looking for is rigorous quantification of uncertainty, then PyMC3, or even a quantile regression, is a better approach. 

The suggestion here is another method for generating a point estimate using zero inflated regression. If you look at the methodology section of the paper below you will see that this is a common way that zero-inflated models are implemented in parametric statistical modelling:

https://www.researchgate.net/publication/13859950_Modeling_accident_frequencies_as_zero-altered_probability_processes_An_empirical_inquiry

**Comment by koaning** [comment] 2021-08-29 07:34
I think I'm on board now. Thanks for the extra details! 

I suppose now we may want to discuss methods of implementation. My thoughts; 

1. For the threshold I'm wondering if we need a hyperparameter in the zero inflated model since we also host a [general thresholder that can be used for this](https://scikit-lego.netlify.app/meta.html?highlight=thresholder#Thresholder). If you're unfamiliar you may appreciate [this calmcode](https://calmcode.io/scikit-meta/threshold.html).

**Comment by Garve** [comment] 2021-08-29 09:26
Hello!

1. I think using the Thresholder for this is better.
2. Sounds good, but you have to keep in mind that usually the predict_proba score is **not** close to the real probability that the output on zero. This is only true when the classifier is calibrated well. Check out [this resource](https://scikit-learn.org/stable/modules/calibration.html) for more information. But this is all fine, we should just add it to the documentation, so people don't pass in uncalibrated RandomForestClassifiers, for example.

Best
Robert

**Comment by john-hawkins** [comment] 2021-08-30 03:53
Thanks @koaning @Garve 

I was not aware of the Thresholder, thanks for pointing me toward that.

Thresholder does not appear to work with the ZeroInflatedRegressor.

I just attempted to use it by wrapping it around a classifier that is passed into the initialisation of ZeroInflatedRegressor.

When I attempted to call fit(), I got an error message suggesting that it could not process the parameter 'sample_weight' that was being passed to it. Is this how you were suggesting it be used in this case?

Code and error below:

```
zir = ZeroInflatedRegressor(
    classifier= Thresholder(SGDClassifier(eta0=0.3, learning_rate='adaptive'), threshold=0.4) ,
    regressor=RandomForestRegressor(    
        n_estimators=2000,
        min_samples_leaf=30,
        max_depth=7)
)

zir_pipe = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('zir', zir )
])

zir_pipe.fit(x_train, y_train)
```


---------------------------------------------------------------------------
NotFittedError                            Traceback (most recent call last)
/usr/local/lib/python3.9/site-packages/sklego/meta/zero_inflated_regressor.py in fit(self, X, y, sample_weight)
     85         try:
---> 86             check_is_fitted(self.classifier)
     87             self.classifier_ = self.classifier

/usr/local/lib/python3.9/site-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
     62             if extra_args <= 0:
---> 63                 return f(*args, **kwargs)
     64 

/usr/local/lib/python3.9/site-packages/sklearn/utils/validation.py in check_is_fitted(estimator, attributes, msg, all_or_any)
   1097     if not attrs:
-> 1098         raise NotFittedError(msg % {'name': type(estimator).__name__})
   1099 

NotFittedError: This Thresholder instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
/var/folders/pg/hc95f3p96zsbhqjy97dcp9cw0000gn/T/ipykernel_20759/2788036688.py in <module>
----> 1 zir_pipe.fit(x_train, y_train)

/usr/local/lib/python3.9/site-packages/sklearn/pipeline.py in fit(self, X, y, **fit_params)
    344             if self._final_estimator != 'passthrough':
    345                 fit_params_last_step = fit_params_steps[self.steps[-1][0]]
--> 346                 self._final_estimator.fit(Xt, y, **fit_params_last_step)
    347 
    348         return self

/usr/local/lib/python3.9/site-packages/sklego/meta/zero_inflated_regressor.py in fit(self, X, y, sample_weight)
     88         except NotFittedError:
     89             self.classifier_ = clone(self.classifier)
---> 90             self.classifier_.fit(X, y != 0, sample_weight=sample_weight)
     91 
     92         non_zero_indices = np.where(self.classifier_.predict(X) == 1)[0]

TypeError: fit() got an unexpected keyword argument **'sample_weight'**

**Comment by MBrouns** [comment] 2021-08-30 07:38
Yep that seems to be an issue on the thresholder, it doesn't accept sample_weight. Should be simple enough to fix, I'll submit a PR in a bit

**Comment by MBrouns** [comment] 2021-08-30 07:58
@john-hawkins could you try the version in #481 to see if that fixes your issue?

**Comment by Garve** [comment] 2022-04-11 20:38
Hi!

To push this issue a bit: The above code

```python
zir = ZeroInflatedRegressor(
    classifier= Thresholder(SGDClassifier(eta0=0.3, learning_rate='adaptive'), threshold=0.4) ,
    regressor=RandomForestRegressor(    
        n_estimators=2000,
        min_samples_leaf=30,
        max_depth=7)
)

zir_pipe = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('zir', zir )
])

zir_pipe.fit(x_train, y_train)
```
works for me, at least if you replace `SGDClassifier` with something that provides proba_scores, e.g. `LogisticRegression`. I think we can close this issue then. @koaning @MBrouns @john-hawkins

**Closed as completed** 2022-04-12 09:38 UTC
Labels: enhancement

**Comment by john-hawkins** [comment] 2022-08-02 06:06
Apologies that I became silent on this issue. Thank you @MBrouns 

The remaining element is the suggestion #2.

Given the context of the comments by @koaning  and @Garve above, I will implement an additional parameter flag to indicate whether the final probability should be calculated as an expectation rather than using the classifier as a boolean gate, and then issue a pull request.
