### ISSUE TITLE
[FEATURE] Statsmodels wrapper class

### ISSUE THREAD

**Issue by stephanecollot** [koaning/scikit-lego#67] opened 2019-03-22 16:50 UTC
If you want to use statsmodels for example for regression in a sklearn pipeline

Example
```
class SMWrapper(BaseEstimator, RegressorMixin):
    """ A universal sklearn-style wrapper for statsmodels regressors """
    def __init__(self, model_class, fit_intercept=True, sample_weight=None):
        self.model_class = model_class
        self.fit_intercept = fit_intercept
        self.sample_weight = sample_weight
    def fit(self, X, y):
        if self.fit_intercept:
            X = sm.add_constant(X)
        self.model_ = self.model_class(y, X, sample_weight=self.sample_weight)
        # Elastic net regularized fit _> fit_regularized
        #self.results_ = self.model_.fit_regularized(alpha=10, L1_wt=0.5)
        self.results_ = self.model_.fit()
    def predict(self, X):
        if self.fit_intercept:
            X = sm.add_constant(X)
        return self.results_.predict(X)
```

**Comment by koaning** [comment] 2019-03-23 08:23
I am open to this idea but I'd like to discuss the use-case a bit. 

What is the main feature that statsmodels might bring that scikit lego currently does not offer? To me it mainly seems that feature selection is something that could occur more automatically in a linear regression but besides that I am wondering what the use-case really is. 

What problems would you be able to solve with this approach that cannot be solved currently?

**Comment by koaning** [comment] 2019-07-26 09:06
If the viewing of variables is the issue, this might be better solved by writing a metrics function that gives an overview of a regression.

**Comment by koaning** [comment] 2020-02-11 21:22
Since this is nearly a year old and nothing happened I am closing this manually.

**Closed by koaning** 2020-02-11 21:22 UTC
Labels: enhancement
